name: Debug

on:
  push:
    branches:
      - dll-name
  workflow_dispatch:

jobs:
  # All tests under this job are run with pre-computed libR-sys bindings.
  tests_no_bindgen:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (R-${{ matrix.config.r }} rust-${{ matrix.config.rust-version }})
            
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', rust-version: 'stable-gnu'}

          - {os: macOS-latest,   r: 'release', rust-version: 'stable'}

          - {os: ubuntu-latest,   r: 'release', rust-version: 'stable', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}



    env:
      RSPM: ${{ matrix.config.rspm }}
    
    # PowerShell core is available on all platforms and can be used to unify scripts
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.config.rust-version }}
          default: true
          override: true
          components: rustfmt, clippy

      - name: Set up R (updated)
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          windows-path-include-mingw: false
      
      - name: Configure Windows
        if: startsWith(runner.os, 'Windows')
        run: |
            rustup target add i686-pc-windows-gnu
            rustup target add x86_64-pc-windows-gnu
        env: 
          RUST_VERSION: ${{ matrix.config.rust-version }}

      - name: Run tests
        run : |
          install.packages(c("remotes", "assertthat"))
          remotes::install_local(force = TRUE)
          rextendr::rust_function("fn rust_inc(x : f64) -> f64 { x + 10f64}")
          assertthat::assert_that(rust_inc(42) == 52)
          rextendr::rust_function("fn rust_inc(x : f64) -> f64 { x + 100f64}")
          assertthat::assert_that(rust_inc(42) == 142)
          rextendr::rust_function("fn rust_empty() {}")
          assertthat::assert_that(is.null(rust_empty()))
        shell: Rscript {0}          